version: "3.9"

services:
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx_app
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./app:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - mariadb

  php:
    build: .
    image: elmtarkati/restaurantpos:latest
    container_name: php_app
    restart: always
    volumes:
      - ./app:/var/www/html
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:10.6
    container_name: mariadb_app
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 12345679
      MYSQL_DATABASE: nourapp-b2
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
